### PR TITLE
Add 'addsuffix' make function

### PR DESCRIPTION
**Pull request by jwrightecs**
See:
https://www.gnu.org/software/make/manual/html_node/File-Name-Functions.html#index-addsuffix

### CODE REVIEW

**Comment by mohawk2** [comment]
Thanks! Released as 2.011.

May I ask what you're using Make for, is it just on the command-line? Also, have you looked at https://metacpan.org/pod/GraphViz::Makefile which has a quite neat visualisation script (tkgraphvizmakefile) in it? I'm keen to figure ways to make this thing more useful (e.g. the `--analyse-redundancy` option).

**Comment by mohawk2** [comment]
(Oops, the doc you didn't change addprefix to addsuffix. I'll change on master but won't bother with another release just yet)

**Comment by jwrightecs** [comment]
basically we're looking at it as using it as an alternative to shelling out to 'make' or even requiring make, and for basic change tracking, and analysis at some point

**Comment by mohawk2** [comment]
Fair enough, thanks! If you have feature ideas/requests, feel free to open issues :-)

**Pull request merged**
